language: csharp
dotnet: 1.0.0-preview2-003121
sudo: required
services:
- docker
dist: trusty
mono: none
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
branches:
  only:
  - master
script:
- ./build.sh
env:
  global:
    DOCKER_PASS:
      secure: 6LwMGe217PkQGjY26AmEPXEAWu8q2TU/ca0cJnvZxnxXcR/IOTxEhxBdOtKQF+oUSQaWK6xjDw/rWe8D23NjkPkj4pQD9dRzuADaPooMXCH+amNkbBRa0WKogoK2i54ajoiyMwtH75bxpTDgicT0KRnnzyb3bLK2JxIktrQK4jVJuGu5wlgR6JvBghIZrRkgAQoe061hxXXaL2z8r5Zfu+5tpkDGAPUdtkmJsxwaapa8+So9/TE0bvj3rtiso3QtmVMOyctqRlXFtz34ORpp/AuD8kfm1jBdZnT/BCMIlLLly1sOc/3aDADzky5f4MplplQEZEkH3DYBEeMK46lC/SuieauOls3/14MUBut0u16k009k+T5j+sIFl5WzCqpAlOEuREOoXXx+MH36v3BRtOD4XRK4yo5OkHGnFaP1Oe2m6goEBZpDd8/AgeZp5Au5LItMdb69n8EVyByyjn55K2hBkIdgUlkv02FhP+2OpKz+qHY4pY7RorkRafGsd+RNQJ3PAzpWLzWigdaxgIqI/+YIC7RQ3lIB9ULDwPbS9rmt8EoR98txOKoU/Ou6fm63iAUtiSRPl/xM2NlJh6IWysqziHE4UNUH9x2ykyQWy5YQCc59NfqIP011RuLkrVL9GUkXk64O8IFeNd0Y19kZu8Us1pW2JhqDUrJg+TDfghU=
    DOCKER_USER:
      secure: Qf9K+YYQx6jznlGDHwQe49ZWRgpx0r/3kofM/E5aq36r5sLC1AqZN83VkUIax2BvX95gPAnZ2PhGCzbTQklTz9OIp9WEt9KS8FPoGw5UqNyjnAMhm59wbEfyPSE/ohPPYN1xE+gjMRWrTHAlr03Mna/AlHSGi8uJffUDFsKKnMzM0mZtAZYqoAs8bAXq+bvV7A9/erzscOOODecwOxZt8toXJrdfaQYdINKwnW62KZtjR1FxjIXM/BNJTMU6W9021q4NiZ7hV3FUCVjfF8OYHiD47gFUdMqtz/592hEIpBhEzHTZQ55ZmPjFgk3RiaQeV9q2yj7JNuG3g5jyit7mqVw4kqqyW7K9KY6LeFyVZEAkZjR0dW3hA43BIe9wu4RZfa9SSWGE4BG3qgf9uxFbd5onyVBcpluhOYqFWFO9l/qwpx64Ww0l0tZTMfJlOqc5S2lPbZuEKCzSzcwVotZFro3Dc1njtQTo4SEZwP6QaMIyoj9zssx4UMs/NsugAy5O9NiB1Knv2qNpROLnPhXhXTkfsvWzryN9Qp5N57PtvRpLsOPW2vDQ9XE7AecyypdK4TIupixaQO1W0ToR9k7hhFb4lWUpEZATTJ/f5kvUS/UopFuTF3pnMgXXNTjVxJPk/SzEONs1foOo/hFV8q3zNyyjwwuhUGEiH6BRi9oULTA=
    DOCKER_EMAIL:
      secure: k64MGTxiq8TEOHqTD/ox4eTugGYWfW55EJPyx4PhdLQKX1K+vN1lRLtHtzB0REjZwu4ThU49Xe6rvTz0bNb9KmXa+QNvqnKrKOMNIU6tZtNlxpcJc9xq4ThMj1GY2q5rlqbqkefBer3q6m4ZwF2P8qjqwI9TZKwA+1guJx7q46KW1bkr55PvuHCc48MLKa8vR8WpJDNhCP40zHb4mAdz9Qc/xFrcLbomgjEQUOSXKh36dOpHrnx/kASYKmlyblYxxfjSQurbnhYsgOuZI+JbK1VwIztQoxRMibFQUQf0Jy5C8ugL11AXJmYMEtGb+SzOVMsPB7M7M27khEVERmgq2r9B7ZmABGt026I8V1jxnHNWo36B1cp6ywtcOktAAAbuNpX3/caHLSma+GqCrbWaiYKU8jfmc97fPjkBT/3m8PLPuzXVSBrNDxZBufRWeZEAgfoPjD4JIwfUhz2CGp4JVp1nYtZBDJlkWuKCq/1k+1+QJLPHtV3PhdvfLnxTMEeX5PMWFXcv9eMIIgXSbCknF0IN+hzz2Z6YcKH0BWd2Q6Yti0bW/qRMKpZ9AdXH3fUctrtCbpnF33rbYVggP36T0TvF0bu7PQ71ftZUnUs3I3ZfRTptSlR+6b+YT+z2HJKshVo8wwIqUmTrwOK4tEDqJ5WEUj8swSjDlmHP6f+IIDY=
  matrix:
  - COMMIT=${TRAVIS_COMMIT::6}
after_success:
- export REPO=$DOCKER_USER/k-auth
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- echo $REPO:$TAG:$COMMIT
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:dockerfuntimes-travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
