language: csharp
dotnet: 1.0.0-preview2-003121
sudo: required
services:
- docker
dist: trusty
mono: none
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
branches:
  only:
  - master
script:
- ./build.sh
env:
  global:
    DOCKER_EMAIL:
      secure: Q0z/hMyUp5xpJzMbOFzXW9aGF4WV1Zh/hsQ/6wUy+ImGNlFeoBkuhxqN8sIKpYiBTV08zElL/XhihWhHZuzO9JGJre54vgE0R/MaPGDg4Qv5wNrLfXv0tBVAnA2ilxKfVDboVmGvjlEGHvWKRG2Ku8RrIAvf6qES5uuSxCRG8bAuA8KQalo3oS26F2W8nj3WgNVq+TrCPg/VHD5xDXG8gVFxUToMJIQa3244nNAkCqSOlkeHo8lUjlWF5iLDaC+YVd2vh1q07qPOpDP+eFHTpkXMoNPffCZz+LSwukA9ixUonxXQHS76CzHXKs7TGeWE3r84G/rplTd3KOah2OyjqCejzMSlJ8GdAOIm+WRUvg7dcbsMjkIq2j8J2HIAmn++6c1k+F72Y4KONW8pEH/fd50vUjqEnuExdOliKUqO8v1mVLL8klnGY5KjDAl7nzZXqZ51q0P0TgaY2GorG09V6465aEdoRiAYrQRL8G7a2xrTVrk/bYnLzK6vxjPWFTMSZrjvaiGesHRk8+vXX0sL25BwdXQO+ctY7P/3Ie9ZYql8uYZWEQjTLrfyfgpaKvICmaYx0ah7bKyTpCi0xalMgIuwCvMhFgrQdS5hDmPm3WK6AtZOMDDVDrgSIBfBwFZH65qF6Nt9L66y2A+4970/J1tw4r0tt4iYdSEieDMD4wU=
    DOCKER_USER:
      secure: gWih0HZoNIGbEq/Q9qTUA+SUvb4mijxoAzU7ksRhLf3Mt1iMZ8p2/VULkc/8Cf9DTESnJ3Mlc7GuztLD/+iQXHW7UC6djBuijXLq1ofaD78mu1encx+eGwwPIswaJlBvuWlmvXuczWhnnjtz7NGS7vuomtc4LIFrcWlWRcEqeJ/6bFMubn7Iji1ui/qiqWXi+L0r1KUs+kefaoNdzPj9uZc8eLVfwu1JbQVIptktiqve1GMuxMzfJnrv1/O0x5oMC4DZZjr2032x91W6qa6K0N53VVEoZMDcZIaDDs6kYwzsv/RVN4KqnP2pQEUyHjux6VD0q3uCGzLqf+b95QHN2rolj6e2neFULoOYv+jkgF4HtFTenW+Z7/njkQmoJ5ZLQk836yrFEx6xI0dVK14SF+jORluxv2AW992XC0azSZ4yN6ccFIIvJ+28GC6sPms4YLGAWpFo2apXRMVPp5UFBdrY5XhvEfMTOokdREHs2knVIp8BtzOLvkVMidmxARL7Zv8guQ4ve6inC76Pn4z8LFnXNVFHI8Rg1UhLXinjtEN0i7EMnTYXDsEetN5NUf2GvlV7wtKOW0odgxNlBs8HyN6tppYwk5gRg9pchaxvjDk/P5SON605xWmL/YR8D6v3ZgS2v3xcnFhHcHS8jHaH5LJ7vOh3aRJmwFw2nBVvjPs=
    DOCKER_PASS:
      secure: TxcQqcnZfKgE0iS+WuiACjIhGz0GB8tUCtnCCjprICO+L8dnrhQo2AL0n7Kjip61H8t2MIleqlk1lWn+J4hn9+oBXeFbbi+x2gf7huZnyhyEtL4B59TrxcdPDU1utb50nq2AkXH+mkv9u0zLR1bNEzX0SrdCjUOB/7o3U0SkiK8bi3Vuftk6D1O3T4gPEYfKO2Sgz8aBfv09ASyro70HK2buYzDPPS+lGNi+KVbI/lp0lOoqX7moz1iFcjGvTichM63d6CXKH4yS1qllci7LZCcQgL1oodZ0iY9ZZobuYx4kCLW/+vtYMPGDPDh9Q1d4Z4v3yeJbNPksBUPex+vyhTdjrmwmOLgHrgYpMj4rw39aXvxFOSNv9cbmuRxw6mE0UwV1FZNDPwPKZt03NbU39zvVjmITQIuIH4rrfKKYjk2koIG0++0nz1krV52iicPZOuu92xqHn6J0BwnaeJgowEq/wdw9sU2AvGIw/vO3nE5l31Wl7KMMlMF6uGniA2A/YmAjmc04BKCPfCDCoic0StRyhuwyISgCsZeS1jVcnB/RZHL77nLPfwOAPjxg8vetVVXZLzLv4DKDsFArgzudN9v2CvQBtJs57giQm7KmpZh454FMZ7l8hHBxygxJFjNxtOdu08g5Rz7GZ/z55lxYMlpwdag85Byxt06ySOiDmEE=
  matrix:
  - COMMIT=${TRAVIS_COMMIT::6}
after_success:
- export REPO=$DOCKER_USER/k-auth
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- echo $REPO:$TAG:$COMMIT
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:dockerfuntimes-travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
