language: csharp
dotnet: 1.0.0-preview2-003121
sudo: required
services:
- docker
dist: trusty
mono: none
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
branches:
  only:
  - master
script:
- ./build.sh
env:
  global:
    DOCKER_EMAIL:
      secure: Uo0tdxbWcWQbjgnBH7pxFP0/WKb8xhhs9hWVDIKn8KrVPiXk0C5bG9444/e0a/fsx1NQcCghfoCOvuOfQSp6UTFp2KX32ROpNFqjQPyoFpVQykm37tv8aUSsoe2DPy+9dbwygNS+rTboPXbPEP7eRdbLZxzdBOhKYlcYg6bctmdafj5aC8mIkL4ANZUhTy9cST0XP6qBFgdZmZGbz2iqhZfqrs0peGxB0sTJPjY+8xthXkr51HOSq1PhWEAwJoZUizA/GsT6pZm0xq6C5VdCTSHJZoH0jL2XlRGxIihboKnDP30YKRFKrq+dx18JHq4/6wAsKFrg7B5+n9Yc7XFaAEx0K7AI0PP6x/80l9e8x+zEBAWFvSvp5vHR29QzDCnwDJyRWzqsVDRFSp+Y/vtFHXxsrjHPofuxz75JqCP4tykOSjAde6UW/iqyKALKk/PsDQFOC23YRsiQBudfMFXIarzZRd/Tzk9IFCVhGcx7Tgzytq77niX+37z1rplevmTTAQIVGvhe3xQOe2sRaVy5rwRWTf1AbLEEg4WjXx/D2iWgluauBoNAc2ptZ+8Kmz4aKxVYtI0r6oROemikTL5dtleAbfAC4MNsrwJFAANQYvtbDSAgr0/59cTH22uF4rgKR/gJdoPjeOGwFyGg9jeNNe/B28iz0sM3WOqje9a+NHs=
    DOCKER_USER:
      secure: HNTQhhBGPgrNKtxl8np6Hvx0lgoJHa0t8cvdpUUM9Yh7DEJtodHv1fu3sSRqvItbucp63EV7Z/dTDBsi+BMOx9uCDkN6zZjvcb4hgQMJYgt03NfzPGinViUCWMj16WA79atoQKQu+9C7SWIuXqbHeyh4OIGvXWt59CA46XVXTNnlp1hNvyAey0GXZuAjE5gsgMfU7v6Ufo9IspbwmjHofYVTryyAbCqY0Gp46bQFYHdOnmNMHrAaf2Y2SBrUxLGCk8MMLEY5OlsqphZpJFGNs0os4hZ+wduYLn6XOiZusAwG0B/sbgYGW6hFGt33vmQ7gXl43cTXXSmb+TXqntdQhOEJkZy5nj34y2UJhjMBXbuBuGXgziUHlc+XSLt0OwTX0F6lt4NopmFFjJNs8FlGQeOX04yMMyP7ksS3XOVXwo0RMQKlH/8pmYjcAqDVQnR8n1qI1NmU6WdBOfZKnUSPHfq7JCutyfdZ31zES64+mU3XzIK4CF2xLTJ40lpBHb3YnUqUM5SsSulcdqHA9Asv12iW7qnZJ0ov+vncJRr12+MR+kL/8jYEeLD/DpKfogApTxTSgEtsuJtmlLNbwpbwpVhXOoV/cC6p3P4mh591r2BBVeQWO0SwRHW6S0nLeo3TVAecCxf3HqzIfE5M5Oet5HV2b/RNEP/HHdCaPWLMl9w=
    DOCKER_PASS:
      secure: GbEjF63jC39PQDg8+7FuVHUaaz5Jh158b71eKUIrtAfgHP/+FAOCX27IUQMbCeTrYaKsvUC50yMdM2+13Ha/cwNy5iNOhHc7Gm340YnOWtNE804d+gIYuo+mD8BryROKh2N1Q05vbWAFTZk+RIW48xFFBg4MKIyYZQb5HKGO11UzzsbHNOKxQa7fOQf2pBA16w5ZkIlNbsrjrIxrEYlUfra35DN8h9i6HoabchJ+g6qelPhwfYW16wjSEsXmAMMxo/yejY+DhEOUmFwTxFBYI9l7VZFH+V/jKt8l411aEO+a5eqKqYAavac8Jz5VPA9MO2DIh1Xadl2GYsWlgigiSfKlkyrfrJSmRLDvAjsbDy5K37IMJe87ZLiTTiQF1gYMzmlaQpDMRLKzFuh8d91AMnCRonO0/ckztxJvZL0Fol7h1WzDjQkTno63WuzunfI/B0Nkf7n8DFmaeQbO+0yTwbp3fZLP6IpB8Gg9+gd2tJwS9/aqBBz10MOZGmGsmtWT0Z+UhNHhToYaChsl3WL89K/WdP8PbB+hSYzDryvqfN0FZTzBUex0gqNS0w7uh1e68Zq9+Ndghf/olAtQJwVS6IceJDrO52ztWfr8dltOtlsxAksed+AsSdgslRzF0wRcVIvUTSa+XFHLCBzjUdP4xtZfhHL0pq0DcZ7Z6akuHJI=
  matrix:
    - COMMIT=${TRAVIS_COMMIT::6}
after_success:
  - export REPO=$DOCKER_USER/k-auth
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo $REPO:$TAG:$COMMIT
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:dockerfuntimes-travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
