language: csharp
dotnet: 1.0.0-preview2-003121
sudo: required
services:
- docker
dist: trusty
mono: none
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
branches:
  only:
  - master
script:
- ./build.sh
env:
  global:
      secure: w3tGh7TkXkd7LTQUV12rIliSwBKd3/itnEOaUjbRNWmPhdPL8Sa0SV6VOX/nxsY9dJRl3Wszo3WzEk64MbPWjq+0hBcLkcgrtE48RsxcrJRSI6xdvqQ2jio52hNy/xA0TF7ZlALB09p4uK/tQObUxZTMXlBT7tAd0w3sMJjAIZNLL5T66ZJ6lGnizbsAknAq6qn45U98NumveppV0x6fVWtAxOfsK+ujZIptcEboAYHYbcTykdfV7asWWolfFayKFGzTq8+Lq+4RPOeaobOLkxjAtCyCnofDcEKkv3JAby+K5VP2ASa11jj0HerOIbA948w5lTET56YvkneaF6jcUs+DDyKt8WPn0MjbdbmP4vpsgFGl0TEPU7aNS1Kn3skaO/GwrF6qsk56YD0ML82ihAGuuAnu8hAWrt87HfuaVLTIpLu86e3ENvPEgi3fbg+NHhItGqPO8yp5jgekTSnkbx1ggMqiPcaXzNhJ0qlK2HljQeGgMs4RgCHyRyac3ESKammgS9uwvLafZVsrPzr1We99gcLgVUo7zrwurEd3DtRBJ8kYLiyFFiWIfDahDC/nPFz00CVA93GOUflt6vpNcnwxoqcaBwfEhr9s15skJmClGkRrb83M8DM4Zc/YKQrZPZfT26YJMuUnJTO3ELCMQo+fUpguqVCYxSgqygfsOjs=
      secure: qagQUFj1bSsJrnQWy7vM2+sN790cymtxnQwxlFUEtqegi3isNUrUV03kOvt/02PMvBuIpAhEiIK6UShHjOzSrMhiKRA4MfrwG8R6ZCw1FgAK+D8MLwR81K7h1cI1VTVtXZAFx+hGeHBoWoNBE3TwfsHB0tf+xYkiUXWLhPxxvXAlgKwBbLE2sH6KtbwDMKkndkmEKCVsoP8HnXZX1gixRyICFJHjOsg6mjoJqlAzlK1wd7AmhRfZqYsxI+wxQx1Vyt10uTQUSJ0OIxdGi3nQo5xhIMPlNJLXeOyFoknoYOUILHI0cqAuNvIEbHmtqK25hPXwmTCX1YCWT03tuGDZR4SKRXfjrI16DO4e+qjrp77tTojymwdvOEg7mtKqLyJNQo7OVrB/sTdf3dtPoDRWXkJabSg5MIYVk5CddI/Y4bzHYZWW8EHTWEWOYlFgZs8dDUmavo66wN7Y9+uhsPVsd2h+ZmQZtzGa7jyGZVoA0KXGR3smAepH1SAkO8tIn3IUiaiHzxduzSVbeCxB+GZe36K4S392iLT9GwBsqriAZrlEIHE/eL3nJiBMIyzc+aYm2xOhYJQiSgXPipwgQjiTX+MhFbJUSt93w51mkEGoEwWxGiLqqs4bjJgIGfyLXZPBcRm8piPoFDcYYYK0FTph6RG6FdU2T4Abbm0a0O3UGHo=
      secure: iLi8xMBc9oazYLvwDt7RhgOsTCMvs9Vv4y2NFNYJH1tzF5RJxRaDtCiceq9z33hTAiLF9MM3FOYt8/EZ81ReOAp+i4icjm62DtKn6e2TVES3F3l9iTSeLA2e2RfvK0kbQpXQjo3vB9ixOHxCIteK+kz3VgInLyRBRo4t725b4EcovQ1DA8xK0LWX/vGqZBjI/cIq0cZxK9V8raTorsX5x+LELZsehdhX16m8wgBzRqv1gLq4H2g4VexlI/SdL07rbJKqVUdkGAOKDoRrL6Yx+Pgnn5SuZNtrBpYjgK5n8vYlJiT3ms+RE9X3tkNKPJJ4lIBSfql1i+WtQ9T1r/AXYgbjOkluwpnXxQpqOOWFNB0d0zIoj9glgmklQaT5+fAGMpBcSgCI8mjsOdeYontjC2QuBXInqTsYzLQi4d3Zu4KPeiqVqvafS7PAvkgfkSZod2P1vergCzoDUJqgQBpClLM09jNr29kl172UhlGSmZojuYpLznhVG7prg4OpfJgp2HeD7Ayk7jCM1KVEPj2+SnGRkBK0UigTJasYIcA/rGxTm6PPy49fFg+iLUrdVpsLdtfr5QXdffi155+bFEsxHMP6Me1mt1DO20GxufN9sQcf7hB6RwcXsouJEpIhZ2jen2P3K4NwXH6BZRh9OajH4DfXrNcholWKl2J2r8jP+1s=
  matrix:
  - COMMIT=${TRAVIS_COMMIT::6}
after_success:
- export REPO=$DOCKER_USER/k-auth
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- echo $REPO:$TAG:$COMMIT
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:dockerfuntimes-travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
